# Generated by Django 4.2.21 on 2025-05-13 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientusage',
            name='unit',
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='frequency',
            field=models.CharField(choices=[('PER_BOX', 'Per Meal Box'), ('WEEKLY', 'Weekly Total'), ('DAILY', 'Daily Total')], default='PER_BOX', help_text='Defines how the component quantity/nutrition is accounted for (e.g., per meal box, weekly total).', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredientusage',
            name='quantity',
            field=models.FloatField(help_text='Amount of the ingredient in grams (g)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
