# Generated by Django 5.0.14 on 2025-05-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ingredientusage_unit_mealcomponent_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='default_rda_female',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='default_rda_male',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='upper_limit',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='source_notes',
            field=models.TextField(blank=True, help_text='e.g., Source of RDA data, general notes about the nutrient', null=True),
        ),
        migrations.CreateModel(
            name='DietaryReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_data_category', models.CharField(help_text="Category from the source DRV data, e.g., 'Carbohydrates', 'Vitamins'", max_length=100)),
                ('target_population', models.CharField(help_text="e.g., 'Adults', 'Infants 7-11 months'", max_length=100)),
                ('age_range_text', models.CharField(help_text="Age range as text from the source, e.g., '≥ 18 years', '7-11 months'", max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NO_SAY', 'Prefer not to say'), ('OTHER', 'Other')], help_text='Gender specificity of the DRV (Male, Female, or applies to both if null/blank)', max_length=10, null=True)),
                ('frequency', models.CharField(help_text="Frequency of intake, e.g., 'daily'", max_length=50)),
                ('value_unit', models.CharField(help_text="Unit for AI, AR, PRI, RI, UL values, e.g., 'g', 'mg', 'E%'", max_length=20)),
                ('ai', models.FloatField(blank=True, null=True, verbose_name='Adequate Intake (AI)')),
                ('ar', models.FloatField(blank=True, null=True, verbose_name='Average Requirement (AR)')),
                ('pri', models.FloatField(blank=True, null=True, verbose_name='Population Reference Intake (PRI)')),
                ('ri', models.FloatField(blank=True, null=True, verbose_name='Reference Intake (RI)')),
                ('ul', models.FloatField(blank=True, null=True, verbose_name='Tolerable Upper Intake Level (UL)')),
                ('nutrient', models.ForeignKey(help_text='The specific nutrient these values refer to.', on_delete=django.db.models.deletion.CASCADE, related_name='drvs', to='api.nutrient')),
            ],
            options={
                'verbose_name': 'Dietary Reference Value',
                'verbose_name_plural': 'Dietary Reference Values',
                'ordering': ['nutrient__name', 'target_population', 'age_range_text', 'gender'],
                'unique_together': {('nutrient', 'target_population', 'age_range_text', 'gender', 'source_data_category', 'value_unit')},
            },
        ),
    ]
