# Generated by Django 5.0.14 on 2025-05-14 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_nutrient_default_rda_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_portion_id', models.IntegerField(blank=True, db_index=True, help_text='The FDC ID for this specific portion entry (foodPortion.id from FDC data, if available).', null=True)),
                ('amount', models.FloatField(help_text="The quantity of the measure unit (e.g., 1 for '1 cup', 0.5 for '0.5 piece').")),
                ('portion_description', models.CharField(help_text="Full description of the portion (e.g., '1 cup', '1 slice (1 oz)', '100 g'). From FDC portionDescription or constructed.", max_length=100)),
                ('gram_weight', models.FloatField(help_text='The weight of this portion in grams.', validators=[django.core.validators.MinValueValidator(0)])),
                ('modifier', models.CharField(blank=True, help_text="Portion modifier (e.g., 'small', 'large', 'piece', or an FDC code like '10205'). From FDC modifier.", max_length=100, null=True)),
                ('measure_unit_name', models.CharField(blank=True, help_text="Name of the measure unit (e.g., 'cup', 'tbsp', 'piece'). From FDC measureUnit.name.", max_length=50, null=True)),
                ('measure_unit_abbreviation', models.CharField(blank=True, help_text="Abbreviation of the measure unit (e.g., 'cup', 'tsp'). From FDC measureUnit.abbreviation.", max_length=50, null=True)),
                ('sequence_number', models.PositiveIntegerField(blank=True, help_text='Order of this portion description for the food item.', null=True)),
                ('data_points', models.PositiveIntegerField(blank=True, help_text='Number of samples used to determine portion weight.', null=True)),
                ('ingredient', models.ForeignKey(help_text='The ingredient this portion information belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='food_portions', to='api.ingredient')),
            ],
            options={
                'ordering': ['ingredient__name', 'sequence_number', 'gram_weight'],
            },
        ),
    ]
