# Generated by Django 5.0.14 on 2025-05-15 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_foodportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='custom_nutrient_targets',
            field=models.JSONField(blank=True, default=dict, help_text='Store custom nutrient targets, e.g., {"NutrientID_or_Name": {"target": 100, "unit": "mg"}}', null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='servings_per_day_per_person',
            field=models.PositiveIntegerField(default=1, help_text='e.g., How many meal boxes/main servings per person per day this plan provides nutrition for.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
