# Generated by Django 5.0.14 on 2025-05-15 17:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_personprofile_custom_nutrient_targets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='custom_protein_target_g',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='protein_target_strategy',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='target_calories_override',
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='custom_nutrient_targets',
            field=models.JSONField(blank=True, default=api.models.get_default_nutrient_targets, help_text='Store custom nutrient targets, e.g., {"NutrientName": {"target": 100, "unit": "mg", "is_override": true}}'),
        ),
    ]
