# Generated by Django 5.0.14 on 2025-05-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_personprofile_custom_protein_target_g_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="meal_components",
        ),
        migrations.CreateModel(
            name="MealPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_people",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific people this meal component instance is assigned to in this plan. If for all, all plan's people will be linked.",
                        related_name="meal_plan_items",
                        to="api.personprofile",
                    ),
                ),
                (
                    "meal_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_plans_as_item",
                        to="api.mealcomponent",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="api.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_plan__name", "meal_component__name"],
            },
        ),
    ]
