# Generated by Django 5.0.14 on 2025-05-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mealplan_meal_components_mealplanitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(help_text='e.g., Vitamin C, Protein. This is the canonical name.', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='NutrientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="An alternative name or symbol for a nutrient (e.g., 'Vitamin B2', 'Thiamin'). Must be unique.", max_length=255, unique=True)),
                ('nutrient', models.ForeignKey(help_text='The canonical nutrient this alias refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.nutrient')),
            ],
            options={
                'verbose_name_plural': 'Nutrient Aliases',
                'ordering': ['name'],
            },
        ),
    ]
