# Generated by Django 5.0.14 on 2025-05-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_nutrient_name_nutrientalias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personprofile",
            name="activity_level",
        ),
        migrations.RemoveField(
            model_name="personprofile",
            name="age_years",
        ),
        migrations.RemoveField(
            model_name="personprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="personprofile",
            name="height_cm",
        ),
        migrations.RemoveField(
            model_name="personprofile",
            name="weight_kg",
        ),
    ]
