# Generated by Django 5.0.14 on 2025-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_personprofile_activity_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Age in years", null=True
            ),
        ),
        migrations.AddField(
            model_name="personprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("NO_SAY", "Prefer not to say"),
                    ("OTHER", "Other"),
                ],
                help_text="Gender of the person",
                max_length=10,
                null=True,
            ),
        ),
    ]
