# Generated by Django 5.0.14 on 2025-05-22 07:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_personprofile_age_personprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutrient",
            name="fdc_nutrient_number",
        ),
        migrations.AlterField(
            model_name="mealcomponent",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("PER_BOX", "Per Meal Box"),
                    ("PER_DAY", "Per Day"),
                    ("PER_WEEK", "Per Week"),
                ],
                default="PER_BOX",
                help_text="Defines how the component quantity/nutrition is accounted for (e.g., per meal box, weekly total).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="nutrient",
            name="category",
            field=models.CharField(
                choices=[
                    ("MACRO", "Macro"),
                    ("VITAMIN", "Vitamin"),
                    ("MINERAL", "Mineral"),
                    ("TRACE", "Trace"),
                    ("GENERAL", "General"),
                    ("ENERGY", "Energy"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Age of the person in years. Used for DRV calculations.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personprofile",
            name="custom_nutrient_targets",
            field=models.JSONField(
                blank=True,
                default=api.models.get_default_nutrient_targets,
                help_text='Custom nutrient targets for this person, overriding default DRVs. Format: {"Nutrient Name": {"target": value, "unit": "unit", "is_override": true}}',
            ),
        ),
    ]
