# Generated by Django 5.0.14 on 2025-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_nutrient_fdc_nutrient_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietaryreferencevalue",
            name="authoritative_rda",
            field=models.FloatField(
                blank=True,
                help_text="The chosen RDA value, derived from PRI or AI during import.",
                null=True,
                verbose_name="Authoritative RDA (PRI or AI)",
            ),
        ),
    ]
